openapi: 3.0.3
info:
  title: "Spring Kafka User Events"
  description: "Spring Kafka User Events"
  version: 1.0.0
servers:
  - url: "http://localhost:30080"
tags:
  - name: Subscriptions
  - name: asde
paths:
  /asdeee:
    post:
      tags:
        - asde
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: asdasdwe
  /subscriptpppppions:
    post:
      tags:
        - Subscriptions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subsub'
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Successful"
        400:
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: "Wrong user age"
components:
  schemas:
    subsub:
      $ref: '#/components/schemas/subsub'
