openapi: 3.0.3
info:
  title: "Spring Kafka User Events DataBase"
  description: "Spring Kafka User Events DataBase"
  version: 1.0.0
servers:
  - url: "http://localhost:30081"
    description: This is server for spring kafka database api

tags:
  - name: "Intervals"
  - name: "Users"

paths:
  /intervals/{from}/{to}:
    parameters:
      - name: from
        description: timestamp of from of interval
        example: 2022-03-11T19:06
        schema:
          type: string
        in: path
        required: true
      - name: to
        description: timestamp of to of interval
        example: 2022-03-11T19:06
        schema:
          type: string
        in: path
        required: true

    get:
      summary: This gets all intervals by given interval
      tags:
        - "Intervals"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessedIntervalSubscriptionsList'
        400:
          description: BAD REQUEST
          content:
            text/plain:
              schema:
                type: string
                example: "parse timestamp error"
  /users:
    get:
      parameters:
        - name: user
          description: user inf
          in: query
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              age:
                type: integer
      operationId: getByUser
      summary: get all processed intervals subscriptions by user information
      tags:
        - "Users"

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessedIntervalSubscriptionsList'
  /users/{id}:
    parameters:
      - name: id
        description: timestamp of from of interval
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: get all processed intervals subscriptions by user id
      tags:
        - "Users"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessedIntervalSubscriptionsList'

components:
  schemas:
    ProcessedIntervalSubscriptions:
      type: object
    ProcessedIntervalSubscriptionsList:
      type: array
      items:
        $ref: '#/components/schemas/ProcessedIntervalSubscriptions'
