apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  labels:
    name: {{ .Release.Name }}-database-service
spec:
  ports:
    - port: 8080
      name: {{ .Release.Name }}-database-port
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-database