kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-database
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      containers:
        - name: {{ .Release.Name }}-database
          env:
            - name: KAFKA_SERVER
              value: {{ .Release.Name }}-cp-kafka-0.{{ .Release.Name }}-cp-kafka-headless.default:9092
            - name: KAFKA_TOPIC
              value: {{ .Values.kafka.dbservice.topic }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: DB_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgresql.default.svc.cluster.local:5432/{{ .Values.postgresql.auth.database }}
          image: daniilkorotaev/spring-postgresql-service:15.0
          ports:
            - containerPort: 8080