apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    name: {{ .Release.Name }}-service
spec:
  ports:
    - port: 8080
      name: {{ .Release.Name }}-port
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  selector:
    app: {{ .Release.Name }}