apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database-service
  labels:
    name: {{ .Release.Name }}-database-service
spec:
  ports:
    - port: 8080
      name: {{ .Release.Name }}-port-database-service
      protocol: TCP
      nodePort: 30081
  type: NodePort
  selector:
    app: {{ .Release.Name }}-database-service